demoHelp/urls.py
from django.conf.urls import url
from demoHelp import views

urlpatterns = [
 url(r'^$',views.help,name='demoHelp'), # demoHelp is the name of the view
]

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
 url(r'^$',views.index,name='index'),
]

nKitchen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views #custom
#from Help import views #custom
from users import views #custom
from django.conf.urls import include
from basicforms import views
from testing_templates import views


urlpatterns = [
    url(r'^$',views.index,name='index'), # index is derived from the views.py in the app folders, the index function within it
    url(r'^main/',include('main.urls')), #appHelloWorld is the /name/ (ex: /main/). *.urls is going to the actual app name
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls')),
    url(r'^help/',include('demoHelp.urls')),
    #url(r'^forms/',views.form_name_view,name='form_name'),
    url(r'^testing_templates/',include('testing_templates.urls')),
]

testing_templates/urls.py
from django.conf.urls import url
from . import views

# template tagging
app_name = 'testing_templates'

urlpatterns=[ # this means if you go to /testing_templates/relative (or other) it will go to that page
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
 url(r'^$',views.users,name='users')
]

basicforms/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(self.date)

testing_templates/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=264,unique=True)

basicforms/forms.py
from django import forms
from django.core import validators

class FormName(forms.Form):
        name = forms.CharField()
        email = forms.EmailField()
        verify_email = forms.EmailField(label='enter your email again:')
        text = forms.CharField(widget=forms.Textarea)
    #    botcatcher = forms.CharField(required=False,
    #                                widget=forms.HiddenInput,
    #                                validators=[validators.MaxLengthValidator(0)]                                    )

        def clean(self):
            all_clean_data = super().clean()
            email = all_clean_data['email']
            vmail = all_clean_data['verify_email']

            if email != vmail:
                raise forms.ValidationError("make sure all emails match!")


#        def clean_botcatcher(self):
#            botcatcher = self.clean_botcatcher['botcatcher']
#            if len(botcatcher) > 0:
#                raise forms.ValidationError("GOTCHA BOT!")
#            return botcatcher

users/forms.py
from django import forms
from users.models import User

class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

basicforms/views.py
from django.shortcuts import render
from . import forms
# Create your views here.

def index(request):
    return render(request, 'basicforms/index.html')

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])

    return render(request, 'basicforms/form_page.html',{'form':form})

demoHelp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request): # request can be any word
#   return HttpResponse("Hello World!")# works.
    my_dictionary = {'insert_me':"Hello I am from views.py!"}
    return render(request,'appHelloWorld/index.html',context=my_dictionary)

def help(request): # request can be any word
#   return HttpResponse("Hello World!")# works.
    help_dict = {'help_insert':"HELP PAGE"}
    return render(request,'demoHelp/help.html',context=help_dict)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from main.models import Topic,Webpage,AccessRecord
# Create your views here.

def index(request): # request can be any word
#   return HttpResponse("Hello World!")# works.
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}
    return render(request,'main/index.html',context=date_dict)

    #my_dictionary = {'insert_me':"Hello I am from views.py!"}
    #return render(request,'appHelloWorld/index.html',context=my_dictionary)

testing_templates/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'testing_templates/index.html')

def other(request):
    return render(request,'testing_templates/other.html')

def relative(request):
    return render(request,'testing_templates/relative_url_templates.html')

users/views.py
from django.shortcuts import render
#from django.http import HttpResponse
from users.models import User
# Create your views here.
def index(request):
    return render(request,'users/index.html')

def users(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error form  invalid')
    return render(request,'users/users.html',{'form':form})





    #user_list = User.objects.order_by('last_name')
    #user_dict = {'users':user_list}
    #return render(request,'users/users.html',context=user_dict)

templates/appHelloWorld/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>First App</title>
    <link rel="stylesheet" href="{% static "css/mystyles.css" %}"/>
  </head>
  <body>
      <h1>Hello this is index.html. </h1>
      <h2>Here's a picture of green lantern! </h2>
      <img src="{% static "images/g_lantern.jpg" %}" alt="Oops!">"
    <!---  {{ insert_me }}-->
  </body>
  </html>

templates/basicforms/form_page.html
<!DOCTYPE html>

<html>
  <head>

    <meta charset="utf-8">
    <title>HOME</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <h1> Forms page -</h1>
  <body>
    <h1> fill out form! </h1>
    <div class="container">
      <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>

  </body>
  </html>

templates/basicforms/index.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>

  <body>
    <div class="container">
          <div class="jumbotron">
      <h1> Welcome to home page -</h1>
        <h2> Go to /forms-</h2>
    </div>
        </div>

  </body>
  </html>

templates/demoHelp/help.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>First App</title>
  </head>
  <body>
      <h1>Hello this is the help page </h1>
      {{ help_insert }}
  </body>
  </html>

templates/main/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Main Page</title>
    <link rel="stylesheet" href="{% static "css/mystyles.css" %}"/>
  </head>
  <body>
    <h1>Hi, welcome to Main/index!</H1>
      <h2>Here are your access records: </h2>

      <div class="accessrecords">
          {% if access_records %}
          <table>
            <thead>
              <th>Site Name</th>
              <th>Date Accessed</th>
            </thead>
            {% for acc in access_records %}
            <tr>
              <td>{{ acc.name }}</td>
              <td>{{ acc.date }}</td>
            </tr>
            {% endfor %}
          </table>
          {% else %}
          <p>NO ACCESS RECORDS FOUND!</p>
          {% endif %}
      </div>
  </body>
</html>

templates/main/index0.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>First App</title>
    <link rel="stylesheet" href="{% static "css/mystyles.css" %}"/>
  </head>
  <body>
      <h1>Hello this is index.html. MAIN PAGE </h1>
      <h2>Here's a picture of green lantern! </h2>
      <img src="{% static "images/g_lantern.jpg" %}" alt="Oops!">"
    <!---  {{ insert_me }}-->
  </body>
  </html>

templates/testing_templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> Welcome to index </h1>

  </body>
</html>

templates/testing_templates/other.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1> Welcome to other  </h1>
  </body>
</html>

templates/testing_templates/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1> Welcome to relative url templates  </h1>
<a href="{% url 'testing_templates:other' %}">THE OTHER PAGE</a>
<a href="{% url 'admin:index' %}">Admin Page</a>
<a href="{% url 'index' %}">index</a>
  </body>
</html>

templates/users/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Main Page</title>
    <link rel="stylesheet" href="{% static "css/mystyles.css" %}"/>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1>Hi, welcome to Main/index!</H1>
        <h2>Go to /users to sign up! </h2>
      </div>
      <div class="jumbotron">

      <h2>Users:</H2>
      {% if users %}
      <ol>
        {% for person in users %}
        <li> User Info </li>
        <ul>
          <li>First Name: {{ person.first_name }}</li>
          <li>Last Name: {{ person.last_name }}</li>
          <li>Email: {{ person.email }} </li>
        </ul>
        {% endfor %}
      </ol>
</div>
      {% endif %}
  </body>
</html>

templates/users/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1> Please sign up here! </h1>
      <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class='btn btn-primary' value="Submit">
      </form>
    </div>
  </body>
</html>